### ISSUE TITLE
Upload and organize data used for this project

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/rf-shimming-7t#1]
- [x] @dpapp86 Upload data to Gdrive (quick and dirty)
- [x] @jcohenadad Organize according to BIDS and upload to OpenNeuro

**Comment by jcohenadad** [comment]
> Unprocessed, but organised data can be found here:
https://drive.google.com/drive/folders/1ETUQTfLyzobQnHjoOSmyuk2KMBWK91Hn

> Processed data has been uploaded here:
https://drive.google.com/drive/folders/1RZrdh6PpRGurYngu-nkXezBxEJiOvCnz

@dpapp86 I get an access denied for both folders.

**Comment by dpapp86** [comment]
Acces granted

**Comment by jcohenadad** [comment]
Data are now on OpenNeuro: https://openneuro.org/datasets/ds004906
