### ISSUE TITLE
Flip angle maps to nT/V conversion needs better documentation

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/rf-shimming-7t#22]
From the original analysis pipeline written by @dpapp86 :

https://github.com/shimming-toolbox/rf-shimming-7t/blob/a576fb3a0d49582e9ea11ddfbfbc2a286d828eec/Analysis.ipynb#L367-L382

I would like to get clarifications/references about:
- "The costants sum up to 130.492": What is the justification for this?
- "VoltageAtSocket = RefVol * 10**-0.095": Where does the "10**-0.095" come from?
- "it has to be divided by 10 (to get it back into units of FA)": Can we get a justification for this? (eg: reference to the sequence, article, forum post, etc.)

**Comment by dpapp86** [comment]
The code comes from Kyle Gilbert, as per:
https://gitlab.com/cfmm/siemens/matlab/common/-/blob/master/b1maps/readsiemensb1maps.m?ref_type=heads

The TFL_B1map output is in units of 10*Flip Angle. This is, as far as I know, only properly documented in the WIP documentation of the sequence the product TFL mapping sequence was developed from, specifically:
<img width="808" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/8f035cdc-59d4-4ff0-b883-cf69a4b0a0b2">
