### ISSUE TITLE
How to handle segmentations and labeling that requires manual input?

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#24]
Related to #20 

As it stands, the segmentation for some subjects and RF shim cases has to be corrected manually. How should this be handled? Would the user be asked to manually correct the segmentations, as they are currently asked to manually help with the labeling, or should the manually corrected segmentations be uploaded as part of the derivaties folder?

**Comment by jcohenadad** [comment]
upload in derivatives— i’ll take care of it once the analysis pipeline is cleaned up #6

**Comment by jcohenadad** [comment]
Fixed in https://github.com/shimming-toolbox/rf-shimming-7t/pull/6
