### ISSUE TITLE
Fix spinal cord segmentation

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/rf-shimming-7t#31]
Two subjects failing:

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/ba42ca60-1d75-48a6-96e2-dbe1e80cdced)

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/5a713cc8-706a-42e7-978b-1f74f57187e4)

**Comment by jcohenadad** [comment]
Using `-c t2s` they all look good! ✅ 

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/5ea85339-c848-4541-8951-7d1948b51903)

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/b860897e-ae05-441b-a710-263f920fa73f)

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/26900f5f-0462-43de-9919-104981005e2d)

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/fb09c713-6a94-4404-9c43-9f1ff710d0bc)

Except sub-04:

![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/20c9b4c7-d642-4202-8fb6-ffee93122b27)

So I can make a close in the code to use `-c t2` only for sub-04

**Comment by dpapp86** [comment]
Sorry to reopen.

I am not sure I understand. Are we switching back to sct_deepseg_sc for this project?

Have you checked other cases? In my experience, at least half the rf shim cases require some manual correction, especially lower down (slices 0-10). MONAI mislocalized or even fully missed the sc, see here for sub-05, patspec, slice 12
<img width="341" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/d1bd8393-88e0-4afd-9ee8-1c01760d9fbe">

**Comment by jcohenadad** [comment]
> Are we switching back to sct_deepseg_sc for this project?

Yes we are. 

> Have you checked other cases? In my experience, at least half the rf shim cases require some manual correction, especially lower down (slices 0-10)

Yes, QC report is generated. All slices covering C1-T2 look fine to me with the current code.

**Comment by jcohenadad** [comment]
Re-closing as https://github.com/shimming-toolbox/rf-shimming-7t/issues/31#issuecomment-1885746218 is addressed
