### ISSUE TITLE
Why use the CoV reduction scan as the segmentation baseline?

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#37]
The CoV reduction scan is one that has already undergone RF shimming. Is the argument that it is expected to be the one with the smoothest signal intensity, hence the best for segmentation?

**Comment by jcohenadad** [comment]
>  Is the argument that it is expected to be the one with the smoothest signal intensity, hence the best for segmentation?

Yes. We could (should) comment on that in the notebook.
