### ISSUE TITLE
How to segment the MPRAGE scans?

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#39]
Using the CoV scan to keep it consistent with GRE scan approach.

`!sct_deepseg_sc -i {subject}_acq-CoV_T1w.nii.gz -c t1 -qc {path_qc}` sometimes (sub-02 shown) performs a bit bad in the upper cervical levels
<img width="1011" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/528c791a-3b9f-4495-963e-b7059be0e06a">

While
`!sct_deepseg_sc -i {subject}_acq-CoV_T1w.nii.gz -c t1 -qc {path_qc} -kernel 3d` performs better in thew upper levels, and worse close to the C/T boundary.
<img width="1011" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/f7c5426e-f8ad-48d9-b514-5effa8a7ea8d">

On other subjects, this is flipped.

Changing the type of centerline detection algorithm does not seem to influence this.

What is your suggestion?

**Comment by jcohenadad** [comment]
The 2d kernel is good enough, the leaking only concerns a few voxels-- this will be smoothed out anyway:

https://github.com/shimming-toolbox/rf-shimming-7t/blob/9cddd3ea9ff30a3d1e5b11939e74eeed59208e54/data_processing.ipynb#L382C24-L384
