### ISSUE TITLE
Upload code for B1+ map figure generation

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#44]

**Comment by dpapp86** [comment]
Just pinging that I am on it, I just have some trouble with #48

**Comment by jcohenadad** [comment]
> I just have some trouble with https://github.com/shimming-toolbox/rf-shimming-7t/issues/48

That's ok, it's literally one line of ASCII chars. GitHub will survive.

**Comment by dpapp86** [comment]
Closing as per #72
