### ISSUE TITLE
Strange deformation within session for `sub-04`

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/rf-shimming-7t#58]
While working on #57, I noticed strange deformation within a session for `sub-04`:

![anim](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/0f544ba3-ee25-41ed-b826-07fae04796a2)

I suspect the table was moved significantly between these two acquisitions, resulting in drastically different gradient non-linearity distortions. 

@dpapp86 Do you recall something abnormal for this acquisition?

**Comment by dpapp86** [comment]
@jcohenadad Here is what I found:

0, Which two acquisitions are these?

1, The Table Postion DICOM tag is the same for all GRE (and tfl_rfmap and tfl_b1map and MPRAGE) scans
2, The shim settings are all the same across RF shimming approaches
3, The CP mode T2star is the one **WITH** ditrotion correction! Could that explain it? As it stands in our code, **none** of the GRE scans we process have GDC, see #11 
<img width="677" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/b47ec7fe-edc6-4c72-ae66-e577aeb71ace">

**Comment by jcohenadad** [comment]
> 3, The CP mode T2star is the one WITH ditrotion correction! Could that explain it? As it stands in our code, none of the GRE scans we process have GDC, see https://github.com/shimming-toolbox/rf-shimming-7t/issues/11

Ah! Amazing catch! That must be it. I probably uploaded the wrong image for some reasons. Thank you.

**Comment by dpapp86** [comment]
I did a quick eval, every other scan is OK:

<img width="758" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/f6194aa7-9b30-4dab-98ad-03a9032c0873">

And the same is true for the fmap anat scans

**Comment by jcohenadad** [comment]
Fixed in: https://openneuro.org/datasets/ds004906/versions/2.3.0
