### ISSUE TITLE
Clarify: how should the user supply the sudo password

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#78]
I suspect @jcohenadad chiefly runs this as a google colab, while I run it as a local notebook. At least in the local notebook, there is no straightforward way to enter text into the cell (or at least none is pointed to by the notebook), so the notebook hangs on this step:

<img width="1175" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/7c7dfcde-262a-44a2-a402-2ab0f868180e">

I have installed the requirements, and I recall doing so via this notebook, but I have no recollection how I did it. I think I just force-ran it a few times.

**Comment by jcohenadad** [comment]
When the notebook is run locally, this cell should not be run (as instructed after the ℹ️)

**Comment by dpapp86** [comment]
User should RTFM, indeed. Closing.
